# see http://www.appveyor.com/docs/appveyor-yml
image: Ubuntu1804
version: 1.0.{build}
platform: x86
stack: mysql, node 8
clone_depth: 1
init: []
install:
- APPVEYOR_NODE=installed
- APPVEYOR_MONO=installed
- curl https://getopenpetra.com > getopenpetra.sh && chmod a+x getopenpetra.sh && sudo ./getopenpetra.sh devenv
test_script:
- sudo cd /home/op_dev/openpetra && nant recreateDatabase resetDatabase test-without-display
before_deploy:
- sudo cd /home/op_dev/openpetra && nant buildRPM
